//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rat.con {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rat.con.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename {0} is invalid..
        /// </summary>
        public static string mBadInput {
            get {
                return ResourceManager.GetString("mBadInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down n dirty texture atlas packing..
        /// </summary>
        public static string mByline {
            get {
                return ResourceManager.GetString("mByline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string mContinue {
            get {
                return ResourceManager.GetString("mContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        public static string mError {
            get {
                return ResourceManager.GetString("mError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********************************************
        ///{0}
        ///{1}
        ///********************************************.
        /// </summary>
        public static string mHeader {
            get {
                return ResourceManager.GetString("mHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:  packrat &lt;files&gt; [-w &lt;width&gt;] [-h &lt;height&gt;]
        ///.
        /// </summary>
        public static string mHelp {
            get {
                return ResourceManager.GetString("mHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0}: {1}.
        /// </summary>
        public static string mLoaded {
            get {
                return ResourceManager.GetString("mLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify one or more images to pack..
        /// </summary>
        public static string mMissingInput {
            get {
                return ResourceManager.GetString("mMissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packed {0}: {1}.
        /// </summary>
        public static string mPacked {
            get {
                return ResourceManager.GetString("mPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}: {1}.
        /// </summary>
        public static string mProcessed {
            get {
                return ResourceManager.GetString("mProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to packrat 0.1.0.
        /// </summary>
        public static string mTitle {
            get {
                return ResourceManager.GetString("mTitle", resourceCulture);
            }
        }
    }
}
